#   examples/gridworld_utils.jl

# Small utilities for generating a synthetic, labeled, variable-length sequence dataset
# used by the package examples and tests. Purpose is to provide a simple source of sequence 
# data with known latent structure (3 waypoint choices) so embeddings from 
# TransformerAutoencoding.jl can be sanity-checked via clustering and reconstruction metrics.

# DISTRIBUTION STATEMENT A. Approved for public release. Distribution is unlimited.

# This material is based upon work supported by the Under Secretary of War for Research 
# and Engineering under Air Force Contract No. FA8702-15-D-0001 or FA8702-25-D-B002. Any 
# opinions, findings, conclusions or recommendations expressed in this material are those 
# of the author(s) and do not necessarily reflect the views of the Under Secretary of War 
# for Research and Engineering.

# © 2026 Massachusetts Institute of Technology.

# The software/firmware is provided to you on an As-Is basis

# Delivered to the U.S. Government with Unlimited Rights, as defined in DFARS Part 
# 252.227-7013 or 7014 (Feb 2014). Notwithstanding any copyright notice, U.S. Government 
# rights in this work are defined by DFARS 252.227-7013 or DFARS 252.227-7014 as detailed 
# above. Use of this work other than as specifically authorized by the U.S. Government may 
# violate any copyrights that exist in this work.

# SPDX-License-Identifier: MIT

# Written by Sam L. Polk, MIT Lincoln Laboratory

module GridworldUtils

using Random

# build_gridworld_dataset(; cluster_size=10, seed=0)` -> `(seqs, labels)`
export build_gridworld_dataset

# Manhattan distance on 2D grid coordinates (used as a greedy heuristic).
manhattan(x, y) = sum(abs.(x .- y))

# Deterministic grid dynamics: state is a 2-vector [x, y], action is a 2-vector Δ.
next_state(state, action) = state .+ action

# Internal trajectory generator.
# Produces a state-action history by greedily moving to a midpoint and then to the goal.
function _agent(start_pt, end_pt, mid_pt; actions, max_steps::Int = 100, rng::AbstractRNG = Random.default_rng())
    curr_state = start_pt
    state_action_history = Vector{Vector{Int}}()
    iter = 0

    # Phase 1: move toward midpoint.
    while manhattan(curr_state, mid_pt) > 0 && iter < max_steps
        # Evaluate all candidate actions by how close they'd bring us to the target.
        action_dists = [manhattan(next_state(curr_state, a), mid_pt) for a in actions]
        minval = minimum(action_dists)
        idxs = findall(==(minval), action_dists)

        # Break ties randomly to create multiple distinct shortest-ish paths.
        a = length(idxs) == 1 ? actions[idxs[1]] : rand(rng, actions[idxs])

        # Each step is stored as [state; action] (length 4). State is BEFORE action.
        push!(state_action_history, vcat(curr_state, a))
        curr_state = next_state(curr_state, a)
        iter += 1
    end

    # Phase 2: move from midpoint to end.
    while manhattan(curr_state, end_pt) > 0 && iter < max_steps
        action_dists = [manhattan(next_state(curr_state, a), end_pt) for a in actions]
        minval = minimum(action_dists)
        idxs = findall(==(minval), action_dists)
        a = length(idxs) == 1 ? actions[idxs[1]] : rand(rng, actions[idxs])

        push!(state_action_history, vcat(curr_state, a))
        curr_state = next_state(curr_state, a)
        iter += 1
    end

    return state_action_history
end

"""
    build_gridworld_dataset(; cluster_size=10, seed=0) -> (seqs, labels)

Creates a toy dataset of variable-length state-action trajectories in a 2D grid.

..........CCCCCCCCCCG
..........C........BA
..........C.......B.A
..........C......B..A
..........C.....B...A
..........C....B....A
..........C...B.....A
..........C..B......A
..........C.B.......A
..........CB........A
AAAAAAAAAABAAAAAAAAAA
A........BC..........
A.......B.C..........
A......B..C..........
A.....B...C..........
A....B....C..........
A...B.....C..........
A..B......C..........
A.B.......C..........
AB........C..........
SCCCCCCCCCC..........


where S and G indicate common starts and finishes and A, B, and C indicate different paths depending on midpoint goalposts. 

- Start: (0,0)
- Goal:  (10,10)
- Midpoints: (0,5), (5,5), (5,0)

Each trajectory is generated by a greedy agent that:
1) moves toward a selected midpoint, then
2) moves toward the goal.

Outputs:
- `seqs`: Vector of trajectories, each trajectory is `Vector{Vector{Int}}`
  where each inner vector is `[x, y, ax, ay]` (state then action), length 4.
- `labels`: Vector{Int} with values 1..3 identifying which midpoint was used.

Notes:
- This dataset is meant for quick smoke tests (batching, training loops, clustering),
  not for benchmarking planning or RL.
"""
function build_gridworld_dataset(; cluster_size::Int = 10, seed::Int = 0)
    rng = MersenneTwister(seed)

    start_point = [0, 0]
    end_point = [10, 10]
    mid_points = [[0, 5], [5, 5], [5, 0]]

    # 4-neighborhood moves (up/down/right/left).
    action_set = [[0, 1], [0, -1], [1, 0], [-1, 0]]

    seqs = Vector{Vector{Vector{Int}}}()
    labels = Int[]

    # Generate equal counts per midpoint so clustering accuracy can be interpreted.
    for _ in 1:cluster_size
        for (mid_idx, mid) in enumerate(mid_points)
            push!(seqs, _agent(start_point, end_point, mid; actions = action_set, rng = rng))
            push!(labels, mid_idx)
        end
    end

    return (seqs, labels)
end

end # module
